version: "3.8"

services:
  consul:
    image: hashicorp/consul:latest
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      - bluesburguer-network
    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost:8500/v1/status/leader || exit 1
      test: ["CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader"]
      interval: 1m
      timeout: 3s
      retries: 60

networks:
  bluesburguer-network:
    driver: bridge

volumes:
  db_app:
