version: "3.8"

services:
  consul:
    image: hashicorp/consul:latest
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      - bluesburguer-network
    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost:8500/v1/status/leader || exit 1
      test: ["CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader"]
      interval: 1m
      timeout: 3s
      retries: 60
   
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: bluesburguer-order:latest
    container_name: bluesburguer-order
    ports:
      - "30000:8000"
    networks:
      - bluesburguer-network
    depends_on:
      localstack:
        condition: service_healthy
      consul:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONSUL_HOST=consul
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=us-east-1
    volumes:
      - db_app:/var/lib/app
    healthcheck:
      test: "curl --fail --silent localhost:8000/actuator/health | grep UP || exit 1"
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 30s

networks:
  bluesburguer-network:
    driver: bridge

volumes:
  db_app:
