INSERT INTO TB_USER(CPF, EMAIL, CREATION_DATE_TIME) VALUES('074.428.160-10', 'email.usuario@server.com', now()) ON DUPLICATE KEY UPDATE CREATION_DATE_TIME = NOW();

INSERT INTO TB_ORDER(ID, CREATED_TIME, FASE, STEP, UPDATED_TIME, USER_ID) VALUES('12642ba8-66cf-4dd5-8e97-71bd852efcf7', NOW(), 'PENDING', 'ORDER', null, 1) ON DUPLICATE KEY UPDATE UPDATED_TIME = NOW();

INSERT INTO TB_ORDER(ID, CREATED_TIME, FASE, STEP, UPDATED_TIME, USER_ID) VALUES('556f2b18-bda4-4d05-934f-7c0063d78f48', NOW(), 'PENDING', 'ORDER', null, 1) ON DUPLICATE KEY UPDATE UPDATED_TIME = NOW();
